### PR TITLE
Add CMake support

### PR DESCRIPTION
**Pull request by furudbat**
## Features

- batteries included
    - up-to-date raylib version (from master a.k.a 5.5.0-dev)
- use raylib CMake, customizable Variables (like `PLATFORM` etc.)
- quicker start with any IDE, if support CMake 
    - `cmake -DCMAKE_BUILD_TYPE=Release -G Ninja -S . -B build`

### Notes

- github actions are still working with make, this CMake support is just for a smoother local development
- ~~haven't test other build and compilers like emscripten~~ add CMake flags in your IDE `-DCMAKE_C_COMPILER=emcc -DCMAKE_CXX_COMPILER=em++ -DPLATFORM=Web -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_TOOLCHAIN_FILE=/usr/lib/emscripten/cmake/Modules/Platform/Emscripten.cmake  `

image

### CODE REVIEW

**Comment by raysan5** [comment]
@furudbat Why CMake requires 6 files spread all around the project? I don't want to pollute all the project with CMake files... could it be contained in 1-2 files only?

**Comment by furudbat** [comment]
> @furudbat Why CMake requires 6 files spread all around the project? I don't want to pollute all the project with CMake files... could it be contained in 1-2 files only?

Sure thing, just squash some `includes` and `sub_directories`, less fragmentation.

**Comment by raysan5** [comment]
@furudbat thanks! merged!

Please note that gamejam requires project compiled for web, it should be supported by CMake, if possible.

**Comment by furudbat** [comment]
Work fine for me, just need to setup emscripten and some CMake variables (Toolchain), paths:
```cmake
cmake -DCMAKE_C_COMPILER=emcc -DCMAKE_CXX_COMPILER=em++ -DPLATFORM=Web -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_TOOLCHAIN_FILE=/usr/lib/emscripten/cmake/Modules/Platform/Emscripten.cmake -G Ninja -S . -B build-web
```
* you then can find the files in `build-web/src`
* `resources` is also bundled and mapped to `/resources` in the virtual FileSystem, `Loadtexture("resources/bg.png")`
* you can also use `emcmake cmake`, which is a simple wrapper for all the CMake variables emscripten needs

**Pull request merged**
